name: al_quran_tafsir_and_audio
description: "All in one Al Quran App with Translation, Tefsir, Quran Audio Book & Notes Backup"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.14
  media_kit_libs_windows_audio: ^1.0.9
  media_kit_libs_linux: ^1.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dart_appwrite: ^12.1.0
  shared_preferences: ^2.3.4
  dio: ^5.7.0
  gap: ^3.0.1
  connectivity_plus: ^6.1.1
  google_fonts: ^6.2.1
  icons_launcher: ^3.0.0
  archive: ^4.0.2
  simple_icons: ^10.1.3
  appwrite: ^13.1.0
  toastification: ^2.3.0
  clipboard: ^0.1.3
  url_launcher: ^6.3.1
  get: ^5.0.0-release-candidate-9.2.1
  fluttertoast: ^8.2.10
  http: ^1.2.2
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/img/makkah.jpg
    - assets/img/madina.jpeg
    - assets/img/QuranLogo.png


icons_launcher:
  image_path: "assets/img/QuranLogo.png"

  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    web:
      enable: true
    linux:
      enable: true