Map<String, String> nativeName = {
  "Albanian": "Shqip",
  "Amazigh": "Tamazight",
  "Amharic": "አማርኛ",
  "Assamese": "অসমীয়া",
  "Azeri": "Azərbaycan dili",
  "Bambara": "Bamanankan",
  "Bengali": "বাংলা",
  "Bosnian": "Bosanski",
  "Bulgarian": "български",
  "Central Khmer": "ភាសាខ្មែរ",
  "Chechen": "Нохчийн мотт",
  "Chinese": "中文",
  "Czech": "Čeština",
  "Dari": "دری",
  "Divehi": "ދިވެހި",
  "Dutch": "Nederlands",
  "English": "English",
  "Finnish": "Suomi",
  "French": "Français",
  "Ganda": "Luganda",
  "German": "Deutsch",
  "Gujarati": "ગુજરાતી",
  "Hausa": "Hausa",
  "Hebrew": "עברית",
  "Hindi": "हिन्दी",
  "Indonesian": "Bahasa Indonesia",
  "Italian": "Italiano",
  "Japanese": "日本語",
  "Kannada": "ಕನ್ನಡ",
  "Kazakh": "Қазақ тілі",
  "Kinyarwanda": "Ikinyarwanda",
  "Korean": "한국어",
  "Kurdish": "Kurdî",
  "Malay": "Bahasa Melayu",
  "Malayalam": "മലയാളം",
  "Maranao": "Mëranaw",
  "Marathi": "मराठी",
  "Nepali": "नेपाली",
  "Norwegian": "Norsk",
  "Oromo": "Afaan Oromoo",
  "Pashto": "پښتو",
  "Persian": "فارسی",
  "Polish": "Polski",
  "Portuguese": "Português",
  "Romanian": "Română",
  "Russian": "Русский",
  "Sindhi": "سنڌي",
  "Sinhala": "සිංහල",
  "Somali": "Soomaaliga",
  "Spanish": "Español",
  "Swahili": "Kiswahili",
  "Swedish": "Svenska",
  "Tagalog": "Tagalog",
  "Tajik": "Тоҷикӣ",
  "Tamil": "தமிழ்",
  "Tatar": "Татарча",
  "Telugu": "తెలుగు",
  "Thai": "ไทย",
  "Turkish": "Türkçe",
  "Uighur": "Uyghurche",
  "Ukrainian": "Українська",
  "Urdu": "اردو",
  "Uzbek": "O‘zbekcha",
  "Vietnamese": "Tiếng Việt",
  "Yoruba": "Yorùbá"
};
