List<Map<String, dynamic>> allTafsir = [
  {
    "id": 157,
    "name": "Fi Zilal al-Quran",
    "author_name": "Sayyid Ibrahim Qutb",
    "slug": "tafsir-fe-zalul-quran-syed-qatab",
    "language_name": "urdu",
  },
  {
    "id": 159,
    "name": "Bayan ul Quran",
    "author_name": "Dr. Israr Ahmad",
    "slug": "tafsir-bayan-ul-quran",
    "language_name": "urdu",
  },
  {
    "id": 165,
    "name": "Tafsir Ahsanul Bayaan",
    "author_name": "Bayaan Foundation",
    "slug": "bn-tafsir-ahsanul-bayaan",
    "language_name": "bengali",
  },
  {
    "id": 166,
    "name": "Tafsir Abu Bakr Zakaria",
    "author_name": "King Fahd Quran Printing Complex",
    "slug": "bn-tafsir-abu-bakr-zakaria",
    "language_name": "bengali",
  },
  {
    "id": 381,
    "name": "Tafsir Fathul Majid",
    "author_name": "AbdulRahman Bin Hasan Al-Alshaikh",
    "slug": "tafisr-fathul-majid-bn",
    "language_name": "bengali",
  },
  {
    "id": 168,
    "name": "Ma'arif al-Qur'an",
    "author_name": "Mufti Muhammad Shafi",
    "slug": "en-tafsir-maarif-ul-quran",
    "language_name": "english",
  },
  {
    "id": 170,
    "name": "Al-Sa'di",
    "author_name": "Saddi",
    "slug": "ru-tafseer-al-saddi",
    "language_name": "russian",
  },
  {
    "id": 90,
    "name": "Al-Qurtubi",
    "author_name": "Qurtubi",
    "slug": "ar-tafseer-al-qurtubi",
    "language_name": "arabic",
  },
  {
    "id": 804,
    "name": "Rebar Kurdish Tafsir",
    "author_name": "Rebar Kurdish Tafsir",
    "slug": "kurd-tafsir-rebar",
    "language_name": "Kurdish",
  },
  {
    "id": 169,
    "name": "Ibn Kathir (Abridged)",
    "author_name": "Hafiz Ibn Kathir",
    "slug": "en-tafisr-ibn-kathir",
    "language_name": "english",
  },
  {
    "id": 94,
    "name": "Tafseer Al-Baghawi",
    "author_name": "Baghawy",
    "slug": "ar-tafsir-al-baghawi",
    "language_name": "arabic",
  },
  {
    "id": 93,
    "name": "Al-Tafsir al-Wasit (Tantawi)",
    "author_name": "Waseet",
    "slug": "ar-tafsir-al-wasit",
    "language_name": "arabic",
  }
];
List<Map<String, dynamic>> allLanguages = [
  {
    "id": 38,
    "name": "English",
  },
  {
    "id": 174,
    "name": "Urdu",
  },
  {
    "id": 20,
    "name": "Bengali",
  },
  {
    "id": 167,
    "name": "Turkish",
  },
  {
    "id": 40,
    "name": "Spanish",
  },
  {
    "id": 23,
    "name": "Bosnian",
  },
  {
    "id": 49,
    "name": "French",
  },
  {
    "id": 106,
    "name": "Malayalam",
  },
  {
    "id": 138,
    "name": "Russian",
  },
  {
    "id": 118,
    "name": "Dutch",
  },
  {
    "id": 67,
    "name": "Indonesian",
  },
  {
    "id": 74,
    "name": "Italian",
  },
  {
    "id": 76,
    "name": "Japanese",
  },
  {
    "id": 160,
    "name": "Tajik",
  },
  {
    "id": 175,
    "name": "Uzbek",
  },
  {
    "id": 177,
    "name": "Vietnamese",
  },
  {
    "id": 185,
    "name": "Chinese",
  },
  {
    "id": 187,
    "name": "Albanian",
  },
  {
    "id": 33,
    "name": "German",
  },
  {
    "id": 158,
    "name": "Tamil",
  },
  {
    "id": 82,
    "name": "Kazakh",
  },
  {
    "id": 84,
    "name": "Central Khmer",
  },
  {
    "id": 10,
    "name": "Assamese",
  },
  {
    "id": 133,
    "name": "Portuguese",
  },
  {
    "id": 19,
    "name": "Bambara",
  },
  {
    "id": 34,
    "name": "Divehi, Dhivehi, Maldivian",
  },
  {
    "id": 16,
    "name": "Bulgarian",
  },
  {
    "id": 110,
    "name": "Malay",
  },
  {
    "id": 150,
    "name": "Somali",
  },
  {
    "id": 60,
    "name": "Hindi",
  },
  {
    "id": 86,
    "name": "Korean",
  },
  {
    "id": 89,
    "name": "Kurdish",
  },
  {
    "id": 13,
    "name": "Azeri",
  },
  {
    "id": 157,
    "name": "Swahili",
  },
  {
    "id": 58,
    "name": "Hausa",
  },
  {
    "id": 43,
    "name": "Persian",
  },
  {
    "id": 161,
    "name": "Thai",
  },
  {
    "id": 164,
    "name": "Tagalog",
  },
  {
    "id": 137,
    "name": "Romanian",
  },
  {
    "id": 190,
    "name": "Dari",
  },
  {
    "id": 188,
    "name": "Amazigh",
  },
  {
    "id": 6,
    "name": "Amharic",
  },
  {
    "id": 25,
    "name": "Chechen",
  },
  {
    "id": 29,
    "name": "Czech",
  },
  {
    "id": 45,
    "name": "Finnish",
  },
  {
    "id": 56,
    "name": "Gujarati",
  },
  {
    "id": 59,
    "name": "Hebrew",
  },
  {
    "id": 78,
    "name": "Georgian",
  },
  {
    "id": 85,
    "name": "Kannada",
  },
  {
    "id": 95,
    "name": "Ganda",
  },
  {
    "id": 105,
    "name": "Macedonian",
  },
  {
    "id": 108,
    "name": "Marathi",
  },
  {
    "id": 109,
    "name": "Maranao",
  },
  {
    "id": 116,
    "name": "Nepali",
  },
  {
    "id": 120,
    "name": "Norwegian",
  },
  {
    "id": 126,
    "name": "Oromo",
  },
  {
    "id": 131,
    "name": "Polish",
  },
  {
    "id": 132,
    "name": "Pashto",
  },
  {
    "id": 139,
    "name": "Kinyarwanda",
  },
  {
    "id": 142,
    "name": "Sindhi",
  },
  {
    "id": 143,
    "name": "Northern Sami",
  },
  {
    "id": 145,
    "name": "Sinhala, Sinhalese",
  },
  {
    "id": 152,
    "name": "Serbian",
  },
  {
    "id": 156,
    "name": "Swedish",
  },
  {
    "id": 159,
    "name": "Telugu",
  },
  {
    "id": 169,
    "name": "Tatar",
  },
  {
    "id": 172,
    "name": "Uighur, Uyghur",
  },
  {
    "id": 173,
    "name": "Ukrainian",
  },
  {
    "id": 151,
    "name": "Albanian",
  },
  {
    "id": 183,
    "name": "Yoruba",
  }
];

List<Map<String, dynamic>> allTranslationLanguage = [
  {
    "id": 85,
    "name": "M.A.S. Abdel Haleem",
    "author_name": "Abdul Haleem",
    "slug": "en-haleem",
    "language_name": "english",
  },
  {
    "id": 131,
    "name": "Dr. Mustafa Khattab, The Clear Quran",
    "author_name": "Dr. Mustafa Khattab",
    "slug": "clearquran-with-tafsir",
    "language_name": "english",
  },
  {
    "id": 84,
    "name": "T. Usmani",
    "author_name": "Mufti Taqi Usmani",
    "slug": "en-taqi-usmani",
    "language_name": "english",
  },
  {
    "id": 95,
    "name": "A. Maududi (Tafhim commentary)",
    "author_name": "Sayyid Abul Ala Maududi",
    "slug": "en-al-maududi",
    "language_name": "english",
  },
  {
    "id": 79,
    "name": "Abu Adel",
    "author_name": "Abu Adel",
    "slug": "ru-abu-adel",
    "language_name": "russian",
  },
  {
    "id": 86,
    "name": "Office of the president of Maldives",
    "author_name": "Office of the president of Maldives",
    "slug": "dv-unknow",
    "language_name": "divehi, dhivehi, maldivian",
  },
  {
    "id": 19,
    "name": "M. Pickthall",
    "author_name": "Mohammed Marmaduke William Pickthall",
    "slug": "quran.en.pickthall",
    "language_name": "english",
  },
  {
    "id": 75,
    "name": "Alikhan Musayev",
    "author_name": "Alikhan Musayev",
    "slug": "az-alikhan",
    "language_name": "azeri",
  },
  {
    "id": 76,
    "name": "Muhammad Saleh",
    "author_name": "Muhammad Saleh",
    "slug": "ug-saleh",
    "language_name": "uighur, uyghur",
  },
  {
    "id": 83,
    "name": "Sheikh Isa Garcia",
    "author_name": "Sheikh Isa Garcia",
    "slug": "es-isa-garcia",
    "language_name": "spanish",
  },
  {
    "id": 78,
    "name": "Ministry of Awqaf, Egypt",
    "author_name": "Ministry of Awqaf, Egypt",
    "slug": "ru-ministry-of-awqaf",
    "language_name": "russian",
  },
  {
    "id": 81,
    "name": "Burhan Muhammad-Amin",
    "author_name": "Burhan Muhammad-Amin",
    "slug": "ku-burhan-muhammad",
    "language_name": "kurdish",
  },
  {
    "id": 80,
    "name": "Muhammad Karakunnu and Vanidas Elayavoor",
    "author_name": "Muhammad Karakunnu and Vanidas Elayavoor",
    "slug": "ml-karakunnu",
    "language_name": "malayalam",
  },
  {
    "id": 22,
    "name": "A. Yusuf Ali",
    "author_name": "Abdullah Yusuf Ali",
    "slug": "quran.en.yusufali",
    "language_name": "english",
  },
  {
    "id": 20,
    "name": "Saheeh International",
    "author_name": "Saheeh International",
    "slug": "en-sahih-international",
    "language_name": "english",
  },
  {
    "id": 203,
    "name": "Al-Hilali & Khan",
    "author_name": "Muhammad Taqi-ud-Din al-Hilali & Muhammad Muhsin Khan",
    "slug": "",
    "language_name": "english",
  },
  {
    "id": 234,
    "name": "Fatah Muhammad Jalandhari",
    "author_name": "Fatah Muhammad Jalandhari",
    "slug": "ur-fatah-muhammad-jalandhari",
    "language_name": "urdu",
  },
  {
    "id": 57,
    "name": "Transliteration",
    "author_name": "Transliteration",
    "slug": "transliteration",
    "language_name": "english",
  },
  {
    "id": 54,
    "name": "Maulana Muhammad Junagarhi",
    "author_name": "Maulana Muhammad Junagarhi",
    "slug": "ur-junagarri",
    "language_name": "urdu",
  },
  {
    "id": 156,
    "name": "Fe Zilal al-Qur'an",
    "author_name": "Sayyid Ibrahim Qutb",
    "slug": "urdu-sayyid-qatab",
    "language_name": "urdu",
  },
  {
    "id": 151,
    "name": "Shaykh al-Hind Mahmud al-Hasan(with Tafsir E Usmani)",
    "author_name": "Shaykh al-Hind Mahmud al-Hasan",
    "slug": "tafsir-e-usmani",
    "language_name": "urdu",
  },
  {
    "id": 158,
    "name": "Bayan-ul-Quran",
    "author_name": "Dr. Israr Ahmad",
    "slug": "bayan-ul-quran",
    "language_name": "urdu",
  },
  {
    "id": 97,
    "name": "Tafheem e Qur'an - Syed Abu Ali Maududi",
    "author_name": "Syed Abu Ali Maududi",
    "slug": "ur-al-maududi",
    "language_name": "urdu",
  },
  {
    "id": 136,
    "name": "Montada Islamic Foundation",
    "author_name": "Montada Islamic Foundation",
    "slug": null,
    "language_name": "french",
  },
  {
    "id": 135,
    "name": "IslamHouse.com",
    "author_name": "IslamHouse.com",
    "slug": null,
    "language_name": "persian",
  },
  {
    "id": 139,
    "name": "Khawaja Mirof & Khawaja Mir",
    "author_name": "Khawaja Mirof & Khawaja Mir",
    "slug": null,
    "language_name": "tajik",
  },
  {
    "id": 35,
    "name": "Ryoichi Mita",
    "author_name": "Ryoichi Mita",
    "slug": "ja-ryoichi-mita",
    "language_name": "japanese",
  },
  {
    "id": 134,
    "name": "King Fahad Quran Complex",
    "author_name": "King Fahad Quran Complex",
    "slug": null,
    "language_name": "indonesian",
  },
  {
    "id": 153,
    "name": "Hamza Roberto Piccardo",
    "author_name": "Hamza Roberto Piccardo",
    "slug": "hamza-roberto-piccardo",
    "language_name": "italian",
  },
  {
    "id": 161,
    "name": "Taisirul Quran",
    "author_name": "Tawheed Publication",
    "slug": "bn-taisirul-quran",
    "language_name": "bengali",
  },
  {
    "id": 163,
    "name": "Sheikh Mujibur Rahman",
    "author_name": "Darussalaam Publication",
    "slug": "bn-sheikh-mujibur-rahman",
    "language_name": "bengali",
  },
  {
    "id": 162,
    "name": "Rawai Al-bayan",
    "author_name": "Bayaan Foundation",
    "slug": "bn-rawai-al-bayan",
    "language_name": "bengali",
  },
  {
    "id": 210,
    "name": "Dar Al-Salam Center",
    "author_name": "Dar Al-Salam Center",
    "slug": null,
    "language_name": "turkish",
  },
  {
    "id": 211,
    "name": "Dar Al-Salam Center",
    "author_name": "Dar Al-Salam Center",
    "slug": null,
    "language_name": "tagalog",
  },
  {
    "id": 217,
    "name": "Dr. Mikhailo Yaqubovic",
    "author_name": "Dr. Mikhailo Yaqubovic",
    "slug": null,
    "language_name": "ukrainian",
  },
  {
    "id": 229,
    "name": "Sheikh Omar Sharif bin Abdul Salam",
    "author_name": "Sheikh Omar Sharif bin Abdul Salam",
    "slug": null,
    "language_name": "tamil",
  },
  {
    "id": 55,
    "name": "Muhammad Sodiq Muhammad Yusuf (Latin) ",
    "author_name": "Muhammad Sodiq Muhammad Yusuf",
    "slug": "quran.uz.sodik",
    "language_name": "uzbek",
  },
  {
    "id": 143,
    "name": "Muhammad Saleh Bamoki",
    "author_name": "Muhammad Saleh Bamoki",
    "slug": null,
    "language_name": "kurdish",
  },
  {
    "id": 141,
    "name": "The Sabiq company",
    "author_name": "The Sabiq company",
    "slug": "",
    "language_name": "indonesian",
  },
  {
    "id": 140,
    "name": "Montada Islamic Foundation",
    "author_name": "Montada Islamic Foundation",
    "slug": null,
    "language_name": "spanish",
  },
  {
    "id": 214,
    "name": "Dar Al-Salam Center",
    "author_name": "Dar Al-Salam Center",
    "slug": null,
    "language_name": "bosnian",
  },
  {
    "id": 227,
    "name": "Maulana Abder-Rahim ibn Muhammad",
    "author_name": "Maulana Abder-Rahim ibn Muhammad",
    "slug": null,
    "language_name": "telugu",
  },
  {
    "id": 226,
    "name": "Muhammad Shafi’i Ansari",
    "author_name": "Muhammad Shafi’i Ansari",
    "slug": null,
    "language_name": "marathi",
  },
  {
    "id": 233,
    "name": "Dar Al-Salam Center",
    "author_name": "Dar Al-Salam Center",
    "slug": null,
    "language_name": "hebrew",
  },
  {
    "id": 225,
    "name": "Rabila Al-Umry",
    "author_name": "Rabila Al-Umry",
    "slug": null,
    "language_name": "gujarati",
  },
  {
    "id": 224,
    "name": "Abdul-Hamid Haidar & Kanhi Muhammad",
    "author_name": "Abdul-Hamid Haidar & Kanhi Muhammad",
    "slug": null,
    "language_name": "malayalam",
  },
  {
    "id": 235,
    "name": "Malak Faris Abdalsalaam",
    "author_name": "Malak Faris Abdalsalaam",
    "slug": "nl-abdalsalaam",
    "language_name": "dutch",
  },
  {
    "id": 232,
    "name": "African Development Foundation",
    "author_name": "African Development Foundation",
    "slug": null,
    "language_name": "ganda",
  },
  {
    "id": 231,
    "name": "Dr. Abdullah Muhammad Abu Bakr and Sheikh Nasir Khamis",
    "author_name": "Dr. Abdullah Muhammad Abu Bakr and Sheikh Nasir Khamis",
    "slug": null,
    "language_name": "swahili",
  },
  {
    "id": 230,
    "name": "Society of Institutes and Universities",
    "author_name": "Society of Institutes and Universities",
    "slug": "",
    "language_name": "thai",
  },
  {
    "id": 223,
    "name": "Pioneers of Translation Center",
    "author_name": "Pioneers of Translation Center",
    "slug": null,
    "language_name": "tajik",
  },
  {
    "id": 222,
    "name": "Khalifa Altay",
    "author_name": "Khalifa Altay",
    "slug": null,
    "language_name": "kazakh",
  },
  {
    "id": 220,
    "name": "Ruwwad Center",
    "author_name": "Translation Pioneers Center",
    "slug": null,
    "language_name": "vietnamese",
  },
  {
    "id": 144,
    "name": "Sofian S. Siregar",
    "author_name": "Sofian S. Siregar",
    "slug": "nl_sofian_s._siregar",
    "language_name": "Dutch",
  },
  {
    "id": 88,
    "name": "Hasan Efendi Nahi",
    "author_name": "Hasan Efendi Nahi",
    "slug": "al-hasan-efendi",
    "language_name": "albanian",
  },
  {
    "id": 87,
    "name": "Sadiq and Sani",
    "author_name": "Sadiq and Sani",
    "slug": "am-sadiq",
    "language_name": "amharic",
  },
  {
    "id": 50,
    "name": "Jan Trust Foundation",
    "author_name": "Jan Trust Foundation",
    "slug": "ta-jan-trust",
    "language_name": "tamil",
  },
  {
    "id": 49,
    "name": "Ali Muhsin Al-Barwani",
    "author_name": "Ali Muhsin Al-Barwani",
    "slug": "sw-ali-muhsin",
    "language_name": "swahili",
  },
  {
    "id": 48,
    "name": "Knut Bernström",
    "author_name": "Knut Bernström",
    "slug": "sv-knut",
    "language_name": "swedish",
  },
  {
    "id": 128,
    "name": "Cambodian Muslim Community Development",
    "author_name": "Cambodian Muslim Community Development",
    "slug": null,
    "language_name": "central khmer",
  },
  {
    "id": 45,
    "name": "Russian Translation ( Elmir Kuliev )",
    "author_name": "Elmir Kuliev",
    "slug": "quran.ru.kuliev",
    "language_name": "russian",
  },
  {
    "id": 77,
    "name": "Turkish Translation(Diyanet)",
    "author_name": "Diyanet Isleri",
    "slug": "quran.tr.diyanet",
    "language_name": "turkish",
  },
  {
    "id": 39,
    "name": "Abdullah Muhammad Basmeih",
    "author_name": "Abdullah Muhammad Basmeih",
    "slug": "ms-abdullah",
    "language_name": "malay",
  },
  {
    "id": 36,
    "name": "Korean",
    "author_name": "Korean",
    "slug": "ko-unknown",
    "language_name": "korean",
  },
  {
    "id": 30,
    "name": "Finnish",
    "author_name": "Finnish",
    "slug": "fi-unknown",
    "language_name": "finnish",
  },
  {
    "id": 26,
    "name": "Czech",
    "author_name": "Czech",
    "slug": "cs-unknown",
    "language_name": "czech",
  },
  {
    "id": 103,
    "name": "Helmi Nasr",
    "author_name": "Helmi Nasr",
    "slug": null,
    "language_name": "portuguese",
  },
  {
    "id": 74,
    "name": "Tajik",
    "author_name": "AbdolMohammad Ayati",
    "slug": "tg-ayati",
    "language_name": "tajik",
  },
  {
    "id": 23,
    "name": "Azerbaijani",
    "author_name": "Azerbaijani",
    "slug": "az-unknown",
    "language_name": "azeri",
  },
  {
    "id": 101,
    "name": "Alauddin Mansour",
    "author_name": "Alauddin Mansour",
    "slug": null,
    "language_name": "uzbek",
  },
  {
    "id": 53,
    "name": "Tatar",
    "author_name": "Tatar",
    "slug": "tt-unknow",
    "language_name": "tatar",
  },
  {
    "id": 47,
    "name": "Albanian",
    "author_name": "Albanian",
    "slug": "sq-unknown",
    "language_name": "albanian",
  },
  {
    "id": 44,
    "name": "Grigore",
    "author_name": "George Grigore",
    "slug": "ro-grigore",
    "language_name": "Romanian",
  },
  {
    "id": 42,
    "name": "Józef Bielawski",
    "author_name": "Józef Bielawski",
    "slug": "pl-jozef-bielawski",
    "language_name": "polish",
  },
  {
    "id": 41,
    "name": "Norwegian",
    "author_name": "Norwegian",
    "slug": "no-unknown",
    "language_name": "norwegian",
  },
  {
    "id": 106,
    "name": "Magomed Magomedov",
    "author_name": "Magomed Magomedov",
    "slug": "chechen-translation",
    "language_name": "chechen",
  },
  {
    "id": 236,
    "name": "Ramdane At Mansour",
    "author_name": "Ramdane At Mansour",
    "slug": null,
    "language_name": "Amazigh",
  },
  {
    "id": 237,
    "name": "Tzvetan Theophanov",
    "author_name": "Tzvetan Theophanov",
    "slug": null,
    "language_name": "Bulgarian",
  },
  {
    "id": 238,
    "name": "Taj Mehmood Amroti",
    "author_name": "Taj Mehmood Amroti",
    "slug": null,
    "language_name": "Sindhi",
  },
  {
    "id": 125,
    "name": "Shaykh Abu Rahimah Mikael Aykyuni",
    "author_name": "Shaykh Abu Rahimah Mikael Aykyuni",
    "slug": null,
    "language_name": "yoruba",
  },
  {
    "id": 124,
    "name": "Muslim Shahin",
    "author_name": "Muslim Shahin",
    "slug": null,
    "language_name": "turkish",
  },
  {
    "id": 46,
    "name": "Mahmud Muhammad Abduh",
    "author_name": "Mahmud Muhammad Abduh",
    "slug": "so-mahmud-abduh",
    "language_name": "somali",
  },
  {
    "id": 113,
    "name": "Khalifah Altai",
    "author_name": "Khalifah Altai",
    "slug": null,
    "language_name": "kazakh",
  },
  {
    "id": 112,
    "name": "Shaban Britch",
    "author_name": "Shaban Britch",
    "slug": null,
    "language_name": "turkish",
  },
  {
    "id": 38,
    "name": "Maranao",
    "author_name": "Maranao",
    "slug": "mrn-unknown",
    "language_name": "maranao",
  },
  {
    "id": 89,
    "name": "Albanian Translation",
    "author_name": "Sherif Ahmeti\t",
    "slug": "quran.al.ahmeti",
    "language_name": "albanian",
  },
  {
    "id": 56,
    "name": "Chinese Translation (Simplified) - Ma Jain",
    "author_name": "Ma Jian",
    "slug": "quran.zh.ma.jain",
    "language_name": "chinese",
  },
  {
    "id": 32,
    "name": "Hausa Translation(Abubakar Gumi)",
    "author_name": "Abubakar Mahmoud Gumi",
    "slug": "quran.ha.abubakar",
    "language_name": "hausa",
  },
  {
    "id": 108,
    "name": "Ahl Al-Hadith Central Society of Nepal",
    "author_name": "Ahl Al-Hadith Central Society of Nepal",
    "slug": null,
    "language_name": "nepali",
  },
  {
    "id": 37,
    "name": "Malayalam Translation(Abdul Hameed and Kunhi)",
    "author_name": "Cheriyamundam Abdul Hameed and Kunhi Mohammed Parappoor",
    "slug": "quran.ml.abdul.hameed",
    "language_name": "malayalam",
  },
  {
    "id": 43,
    "name": "Portuguese Translation( Samir )",
    "author_name": "Samir El-Hayek",
    "slug": "quran,pt.samir",
    "language_name": "portuguese",
  },
  {
    "id": 51,
    "name": "Thai Translatio (King Fahad Quran Complex)",
    "author_name": "King Fahad Quran Complex",
    "slug": "quran.th.quran.complex",
    "language_name": "thai",
  },
  {
    "id": 111,
    "name": "Ghali Apapur Apaghuna",
    "author_name": "Ghali Apapur Apaghuna",
    "slug": null,
    "language_name": "oromo",
  },
  {
    "id": 115,
    "name": "Abubakar Mahmood Jummi",
    "author_name": "Abubakar Mahmood Jummi",
    "slug": null,
    "language_name": "hausa",
  },
  {
    "id": 31,
    "name": "Muhammad Hamidullah",
    "author_name": "Muhammad Hamidullah",
    "slug": "quran.fr.hamidullah",
    "language_name": "french",
  },
  {
    "id": 29,
    "name": "Hussein Taji Kal Dari",
    "author_name": "Hussein Taji Kal Dari",
    "slug": "fr-hussein-taji",
    "language_name": "persian",
  },
  {
    "id": 208,
    "name": "Abu Reda Muhammad ibn Ahmad",
    "author_name": "Abu Reda Muhammad ibn Ahmad",
    "slug": null,
    "language_name": "german",
  },
  {
    "id": 209,
    "name": "Othman al-Sharif",
    "author_name": "Othman al-Sharif",
    "slug": null,
    "language_name": "italian",
  },
  {
    "id": 133,
    "name": "Abdul Hameed Baqavi",
    "author_name": "Abdul Hameed Baqavi",
    "slug": null,
    "language_name": "tamil",
  },
  {
    "id": 25,
    "name": "Muhamed Mehanović",
    "author_name": "Muhamed Mehanović",
    "slug": "bs-unknown",
    "language_name": "bosnian",
  },
  {
    "id": 221,
    "name": "Hasan Abdul-Karim",
    "author_name": "Hasan Abdul-Karim",
    "slug": null,
    "language_name": "vietnamese",
  },
  {
    "id": 219,
    "name": "Hamed Choi",
    "author_name": "Hamed Choi",
    "slug": null,
    "language_name": "korean",
  },
  {
    "id": 52,
    "name": "Elmalili Hamdi Yazir",
    "author_name": "Elmalili Hamdi Yazir\t",
    "slug": "tr-hamdi",
    "language_name": "turkish",
  },
  {
    "id": 213,
    "name": "Dr. Abu Bakr Muhammad Zakaria",
    "author_name": "Dr. Abu Bakr Muhammad Zakaria",
    "slug": null,
    "language_name": "bengali",
  },
  {
    "id": 199,
    "name": "Noor International Center",
    "author_name": "Noor International Center",
    "slug": null,
    "language_name": "spanish",
  },
  {
    "id": 218,
    "name": "Saeed Sato",
    "author_name": "Saeed Sato",
    "slug": null,
    "language_name": "japanese",
  },
  {
    "id": 228,
    "name": "Ruwwad Center",
    "author_name": "Translation Pioneers Center",
    "slug": null,
    "language_name": "sinhala, sinhalese",
  },
  {
    "id": 126,
    "name": "Besim Korkut",
    "author_name": "Besim Korkut",
    "slug": null,
    "language_name": "bosnian",
  },
  {
    "id": 122,
    "name": "Maulana Azizul Haque al-Umari",
    "author_name": "Maulana Azizul Haque al-Umari",
    "slug": null,
    "language_name": "hindi",
  },
  {
    "id": 120,
    "name": "Shaykh Rafeequl Islam Habibur-Rahman",
    "author_name": "Shaykh Rafeequl Islam Habibur-Rahman",
    "slug": null,
    "language_name": "assamese",
  },
  {
    "id": 127,
    "name": "Muhammad Sodik Muhammad Yusuf",
    "author_name": "Muhammad Sodik Muhammad Yusuf",
    "slug": "",
    "language_name": "uzbek",
  },
  {
    "id": 118,
    "name": "Zakaria Abulsalam",
    "author_name": "Zakaria Abulsalam",
    "slug": null,
    "language_name": "pashto",
  },
  {
    "id": 109,
    "name": "Muhammad Makin",
    "author_name": "Muhammad Makin",
    "slug": null,
    "language_name": "chinese",
  },
  {
    "id": 27,
    "name": "Frank Bubenheim and Nadeem",
    "author_name": "Frank Bubenheim and Nadeem",
    "slug": "de-bubenheim",
    "language_name": "german",
  },
  {
    "id": 33,
    "name": "Indonesian Islamic affairs ministry",
    "author_name": "Indonesian Islamic affairs ministry",
    "slug": "quran.id",
    "language_name": "indonesian",
  },
  {
    "id": 785,
    "name": "Mawlawi Muhammad Anwar Badkhashani",
    "author_name": "Mawlawi Muhammad Anwar Badkhashani",
    "slug": null,
    "language_name": "dari",
  },
  {
    "id": 795,
    "name": "Suliman Kanti",
    "author_name": "Suliman Kanti",
    "slug": "",
    "language_name": "bambara",
  },
  {
    "id": 779,
    "name": "Rashid Maash",
    "author_name": "Rashid Maash",
    "slug": "fr-rashid-maash",
    "language_name": "french",
  },
  {
    "id": 771,
    "name": "Kannada Translation",
    "author_name": "Kannada Translation",
    "slug": "kannada-quran",
    "language_name": "kannada",
  },
  {
    "id": 782,
    "name": "Islamic and Cultural League",
    "author_name": "Islamic and Cultural League",
    "slug": "",
    "language_name": "romanian",
  },
  {
    "id": 796,
    "name": "Baba Mamady Jani",
    "author_name": "Baba Mamady Jani",
    "slug": null,
    "language_name": "bambara",
  },
  {
    "id": 798,
    "name": "Abdul Hamid Silika",
    "author_name": "Abdul Hamid Silika",
    "slug": null,
    "language_name": "yau,yuw",
  },
  {
    "id": 774,
    "name": "The Rwanda Muslims Association team",
    "author_name": "The Rwanda Muslims Association team",
    "slug": null,
    "language_name": "kinyarwanda",
  },
  {
    "id": 840,
    "name": "Abu Bakr Ibrahim Ali (Bakurube)",
    "author_name": "Abu Bakr Ibrahim Ali",
    "slug": "ml-shaikh-aboobakr-ibrahim-ali",
    "language_name": "divehi",
  },
  {
    "id": 819,
    "name": "Maulana Wahiduddin Khan",
    "author_name": "Maulana Wahiduddin Khan",
    "slug": "maulana-wahid-uddin-khan-urdu",
    "language_name": "urdu",
  },
  {
    "id": 831,
    "name": "Abul Ala Maududi(Roman Urdu)",
    "author_name": "Abul Ala Maududi",
    "slug": "maududi-roman-urdu",
    "language_name": "urdu",
  }
];
List<Map<String, dynamic>> allChaptersInfo = [
  {
    "id": 1,
    "revelation_place": "makkah",
    "revelation_order": 5,
    "bismillah_pre": false,
    "name_simple": "Al-Fatihah",
    "name_arabic": "\u0627\u0644\u0641\u0627\u062a\u062d\u0629",
    "verses_count": 7,
    "pages": [1, 1],
  },
  {
    "id": 2,
    "revelation_place": "madinah",
    "revelation_order": 87,
    "bismillah_pre": true,
    "name_simple": "Al-Baqarah",
    "name_arabic": "\u0627\u0644\u0628\u0642\u0631\u0629",
    "verses_count": 286,
    "pages": [2, 49],
  },
  {
    "id": 3,
    "revelation_place": "madinah",
    "revelation_order": 89,
    "bismillah_pre": true,
    "name_simple": "Ali 'Imran",
    "name_arabic": "\u0622\u0644 \u0639\u0645\u0631\u0627\u0646",
    "verses_count": 200,
    "pages": [50, 76],
  },
  {
    "id": 4,
    "revelation_place": "madinah",
    "revelation_order": 92,
    "bismillah_pre": true,
    "name_simple": "An-Nisa",
    "name_arabic": "\u0627\u0644\u0646\u0633\u0627\u0621",
    "verses_count": 176,
    "pages": [77, 106],
  },
  {
    "id": 5,
    "revelation_place": "madinah",
    "revelation_order": 112,
    "bismillah_pre": true,
    "name_simple": "Al-Ma'idah",
    "name_arabic": "\u0627\u0644\u0645\u0627\u0626\u062f\u0629",
    "verses_count": 120,
    "pages": [106, 127],
  },
  {
    "id": 6,
    "revelation_place": "makkah",
    "revelation_order": 55,
    "bismillah_pre": true,
    "name_simple": "Al-An'am",
    "name_arabic": "\u0627\u0644\u0623\u0646\u0639\u0627\u0645",
    "verses_count": 165,
    "pages": [128, 150],
  },
  {
    "id": 7,
    "revelation_place": "makkah",
    "revelation_order": 39,
    "bismillah_pre": true,
    "name_simple": "Al-A'raf",
    "name_arabic": "\u0627\u0644\u0623\u0639\u0631\u0627\u0641",
    "verses_count": 206,
    "pages": [151, 176],
  },
  {
    "id": 8,
    "revelation_place": "madinah",
    "revelation_order": 88,
    "bismillah_pre": true,
    "name_simple": "Al-Anfal",
    "name_arabic": "\u0627\u0644\u0623\u0646\u0641\u0627\u0644",
    "verses_count": 75,
    "pages": [177, 186],
  },
  {
    "id": 9,
    "revelation_place": "madinah",
    "revelation_order": 113,
    "bismillah_pre": false,
    "name_simple": "At-Tawbah",
    "name_arabic": "\u0627\u0644\u062a\u0648\u0628\u0629",
    "verses_count": 129,
    "pages": [187, 207],
  },
  {
    "id": 10,
    "revelation_place": "makkah",
    "revelation_order": 51,
    "bismillah_pre": true,
    "name_simple": "Yunus",
    "name_arabic": "\u064a\u0648\u0646\u0633",
    "verses_count": 109,
    "pages": [208, 221],
  },
  {
    "id": 11,
    "revelation_place": "makkah",
    "revelation_order": 52,
    "bismillah_pre": true,
    "name_simple": "Hud",
    "name_arabic": "\u0647\u0648\u062f",
    "verses_count": 123,
    "pages": [221, 235],
  },
  {
    "id": 12,
    "revelation_place": "makkah",
    "revelation_order": 53,
    "bismillah_pre": true,
    "name_simple": "Yusuf",
    "name_arabic": "\u064a\u0648\u0633\u0641",
    "verses_count": 111,
    "pages": [235, 248],
  },
  {
    "id": 13,
    "revelation_place": "madinah",
    "revelation_order": 96,
    "bismillah_pre": true,
    "name_simple": "Ar-Ra'd",
    "name_arabic": "\u0627\u0644\u0631\u0639\u062f",
    "verses_count": 43,
    "pages": [249, 255],
  },
  {
    "id": 14,
    "revelation_place": "makkah",
    "revelation_order": 72,
    "bismillah_pre": true,
    "name_simple": "Ibrahim",
    "name_arabic": "\u0627\u0628\u0631\u0627\u0647\u064a\u0645",
    "verses_count": 52,
    "pages": [255, 261],
  },
  {
    "id": 15,
    "revelation_place": "makkah",
    "revelation_order": 54,
    "bismillah_pre": true,
    "name_simple": "Al-Hijr",
    "name_arabic": "\u0627\u0644\u062d\u062c\u0631",
    "verses_count": 99,
    "pages": [262, 267],
  },
  {
    "id": 16,
    "revelation_place": "makkah",
    "revelation_order": 70,
    "bismillah_pre": true,
    "name_simple": "An-Nahl",
    "name_arabic": "\u0627\u0644\u0646\u062d\u0644",
    "verses_count": 128,
    "pages": [267, 281],
  },
  {
    "id": 17,
    "revelation_place": "makkah",
    "revelation_order": 50,
    "bismillah_pre": true,
    "name_simple": "Al-Isra",
    "name_arabic": "\u0627\u0644\u0625\u0633\u0631\u0627\u0621",
    "verses_count": 111,
    "pages": [282, 293],
  },
  {
    "id": 18,
    "revelation_place": "makkah",
    "revelation_order": 69,
    "bismillah_pre": true,
    "name_simple": "Al-Kahf",
    "name_arabic": "\u0627\u0644\u0643\u0647\u0641",
    "verses_count": 110,
    "pages": [293, 304],
  },
  {
    "id": 19,
    "revelation_place": "makkah",
    "revelation_order": 44,
    "bismillah_pre": true,
    "name_simple": "Maryam",
    "name_arabic": "\u0645\u0631\u064a\u0645",
    "verses_count": 98,
    "pages": [305, 312],
  },
  {
    "id": 20,
    "revelation_place": "makkah",
    "revelation_order": 45,
    "bismillah_pre": true,
    "name_simple": "Taha",
    "name_arabic": "\u0637\u0647",
    "verses_count": 135,
    "pages": [312, 321],
  },
  {
    "id": 21,
    "revelation_place": "makkah",
    "revelation_order": 73,
    "bismillah_pre": true,
    "name_simple": "Al-Anbya",
    "name_arabic": "\u0627\u0644\u0623\u0646\u0628\u064a\u0627\u0621",
    "verses_count": 112,
    "pages": [322, 331],
  },
  {
    "id": 22,
    "revelation_place": "madinah",
    "revelation_order": 103,
    "bismillah_pre": true,
    "name_simple": "Al-Hajj",
    "name_arabic": "\u0627\u0644\u062d\u062c",
    "verses_count": 78,
    "pages": [332, 341],
  },
  {
    "id": 23,
    "revelation_place": "makkah",
    "revelation_order": 74,
    "bismillah_pre": true,
    "name_simple": "Al-Mu'minun",
    "name_arabic": "\u0627\u0644\u0645\u0624\u0645\u0646\u0648\u0646",
    "verses_count": 118,
    "pages": [342, 349],
  },
  {
    "id": 24,
    "revelation_place": "madinah",
    "revelation_order": 102,
    "bismillah_pre": true,
    "name_simple": "An-Nur",
    "name_arabic": "\u0627\u0644\u0646\u0648\u0631",
    "verses_count": 64,
    "pages": [350, 359],
  },
  {
    "id": 25,
    "revelation_place": "makkah",
    "revelation_order": 42,
    "bismillah_pre": true,
    "name_simple": "Al-Furqan",
    "name_arabic": "\u0627\u0644\u0641\u0631\u0642\u0627\u0646",
    "verses_count": 77,
    "pages": [359, 366],
  },
  {
    "id": 26,
    "revelation_place": "makkah",
    "revelation_order": 47,
    "bismillah_pre": true,
    "name_simple": "Ash-Shu'ara",
    "name_arabic": "\u0627\u0644\u0634\u0639\u0631\u0627\u0621",
    "verses_count": 227,
    "pages": [367, 376],
  },
  {
    "id": 27,
    "revelation_place": "makkah",
    "revelation_order": 48,
    "bismillah_pre": true,
    "name_simple": "An-Naml",
    "name_arabic": "\u0627\u0644\u0646\u0645\u0644",
    "verses_count": 93,
    "pages": [377, 385],
  },
  {
    "id": 28,
    "revelation_place": "makkah",
    "revelation_order": 49,
    "bismillah_pre": true,
    "name_simple": "Al-Qasas",
    "name_arabic": "\u0627\u0644\u0642\u0635\u0635",
    "verses_count": 88,
    "pages": [385, 396],
  },
  {
    "id": 29,
    "revelation_place": "makkah",
    "revelation_order": 85,
    "bismillah_pre": true,
    "name_simple": "Al-'Ankabut",
    "name_arabic": "\u0627\u0644\u0639\u0646\u0643\u0628\u0648\u062a",
    "verses_count": 69,
    "pages": [396, 404],
  },
  {
    "id": 30,
    "revelation_place": "makkah",
    "revelation_order": 84,
    "bismillah_pre": true,
    "name_simple": "Ar-Rum",
    "name_arabic": "\u0627\u0644\u0631\u0648\u0645",
    "verses_count": 60,
    "pages": [404, 410],
  },
  {
    "id": 31,
    "revelation_place": "makkah",
    "revelation_order": 57,
    "bismillah_pre": true,
    "name_simple": "Luqman",
    "name_arabic": "\u0644\u0642\u0645\u0627\u0646",
    "verses_count": 34,
    "pages": [411, 414],
  },
  {
    "id": 32,
    "revelation_place": "makkah",
    "revelation_order": 75,
    "bismillah_pre": true,
    "name_simple": "As-Sajdah",
    "name_arabic": "\u0627\u0644\u0633\u062c\u062f\u0629",
    "verses_count": 30,
    "pages": [415, 417],
  },
  {
    "id": 33,
    "revelation_place": "madinah",
    "revelation_order": 90,
    "bismillah_pre": true,
    "name_simple": "Al-Ahzab",
    "name_arabic": "\u0627\u0644\u0623\u062d\u0632\u0627\u0628",
    "verses_count": 73,
    "pages": [418, 427],
  },
  {
    "id": 34,
    "revelation_place": "makkah",
    "revelation_order": 58,
    "bismillah_pre": true,
    "name_simple": "Saba",
    "name_arabic": "\u0633\u0628\u0625",
    "verses_count": 54,
    "pages": [428, 434],
  },
  {
    "id": 35,
    "revelation_place": "makkah",
    "revelation_order": 43,
    "bismillah_pre": true,
    "name_simple": "Fatir",
    "name_arabic": "\u0641\u0627\u0637\u0631",
    "verses_count": 45,
    "pages": [434, 440],
  },
  {
    "id": 36,
    "revelation_place": "makkah",
    "revelation_order": 41,
    "bismillah_pre": true,
    "name_simple": "Ya-Sin",
    "name_arabic": "\u064a\u0633",
    "verses_count": 83,
    "pages": [440, 445],
  },
  {
    "id": 37,
    "revelation_place": "makkah",
    "revelation_order": 56,
    "bismillah_pre": true,
    "name_simple": "As-Saffat",
    "name_arabic": "\u0627\u0644\u0635\u0627\u0641\u0627\u062a",
    "verses_count": 182,
    "pages": [446, 452],
  },
  {
    "id": 38,
    "revelation_place": "makkah",
    "revelation_order": 38,
    "bismillah_pre": true,
    "name_simple": "Sad",
    "name_arabic": "\u0635",
    "verses_count": 88,
    "pages": [453, 458],
  },
  {
    "id": 39,
    "revelation_place": "makkah",
    "revelation_order": 59,
    "bismillah_pre": true,
    "name_simple": "Az-Zumar",
    "name_arabic": "\u0627\u0644\u0632\u0645\u0631",
    "verses_count": 75,
    "pages": [458, 467],
  },
  {
    "id": 40,
    "revelation_place": "makkah",
    "revelation_order": 60,
    "bismillah_pre": true,
    "name_simple": "Ghafir",
    "name_arabic": "\u063a\u0627\u0641\u0631",
    "verses_count": 85,
    "pages": [467, 476],
  },
  {
    "id": 41,
    "revelation_place": "makkah",
    "revelation_order": 61,
    "bismillah_pre": true,
    "name_simple": "Fussilat",
    "name_arabic": "\u0641\u0635\u0644\u062a",
    "verses_count": 54,
    "pages": [477, 482],
  },
  {
    "id": 42,
    "revelation_place": "makkah",
    "revelation_order": 62,
    "bismillah_pre": true,
    "name_simple": "Ash-Shuraa",
    "name_arabic": "\u0627\u0644\u0634\u0648\u0631\u0649",
    "verses_count": 53,
    "pages": [483, 489],
  },
  {
    "id": 43,
    "revelation_place": "makkah",
    "revelation_order": 63,
    "bismillah_pre": true,
    "name_simple": "Az-Zukhruf",
    "name_arabic": "\u0627\u0644\u0632\u062e\u0631\u0641",
    "verses_count": 89,
    "pages": [489, 495],
  },
  {
    "id": 44,
    "revelation_place": "makkah",
    "revelation_order": 64,
    "bismillah_pre": true,
    "name_simple": "Ad-Dukhan",
    "name_arabic": "\u0627\u0644\u062f\u062e\u0627\u0646",
    "verses_count": 59,
    "pages": [496, 498],
  },
  {
    "id": 45,
    "revelation_place": "makkah",
    "revelation_order": 65,
    "bismillah_pre": true,
    "name_simple": "Al-Jathiyah",
    "name_arabic": "\u0627\u0644\u062c\u0627\u062b\u064a\u0629",
    "verses_count": 37,
    "pages": [499, 502],
  },
  {
    "id": 46,
    "revelation_place": "makkah",
    "revelation_order": 66,
    "bismillah_pre": true,
    "name_simple": "Al-Ahqaf",
    "name_arabic": "\u0627\u0644\u0623\u062d\u0642\u0627\u0641",
    "verses_count": 35,
    "pages": [502, 506],
  },
  {
    "id": 47,
    "revelation_place": "madinah",
    "revelation_order": 95,
    "bismillah_pre": true,
    "name_simple": "Muhammad",
    "name_arabic": "\u0645\u062d\u0645\u062f",
    "verses_count": 38,
    "pages": [507, 510],
  },
  {
    "id": 48,
    "revelation_place": "madinah",
    "revelation_order": 111,
    "bismillah_pre": true,
    "name_simple": "Al-Fath",
    "name_arabic": "\u0627\u0644\u0641\u062a\u062d",
    "verses_count": 29,
    "pages": [511, 515],
  },
  {
    "id": 49,
    "revelation_place": "madinah",
    "revelation_order": 106,
    "bismillah_pre": true,
    "name_simple": "Al-Hujurat",
    "name_arabic": "\u0627\u0644\u062d\u062c\u0631\u0627\u062a",
    "verses_count": 18,
    "pages": [515, 517],
  },
  {
    "id": 50,
    "revelation_place": "makkah",
    "revelation_order": 34,
    "bismillah_pre": true,
    "name_simple": "Qaf",
    "name_arabic": "\u0642",
    "verses_count": 45,
    "pages": [518, 520],
  },
  {
    "id": 51,
    "revelation_place": "makkah",
    "revelation_order": 67,
    "bismillah_pre": true,
    "name_simple": "Adh-Dhariyat",
    "name_arabic": "\u0627\u0644\u0630\u0627\u0631\u064a\u0627\u062a",
    "verses_count": 60,
    "pages": [520, 523],
  },
  {
    "id": 52,
    "revelation_place": "makkah",
    "revelation_order": 76,
    "bismillah_pre": true,
    "name_simple": "At-Tur",
    "name_arabic": "\u0627\u0644\u0637\u0648\u0631",
    "verses_count": 49,
    "pages": [523, 525],
  },
  {
    "id": 53,
    "revelation_place": "makkah",
    "revelation_order": 23,
    "bismillah_pre": true,
    "name_simple": "An-Najm",
    "name_arabic": "\u0627\u0644\u0646\u062c\u0645",
    "verses_count": 62,
    "pages": [526, 528],
  },
  {
    "id": 54,
    "revelation_place": "makkah",
    "revelation_order": 37,
    "bismillah_pre": true,
    "name_simple": "Al-Qamar",
    "name_arabic": "\u0627\u0644\u0642\u0645\u0631",
    "verses_count": 55,
    "pages": [528, 531],
  },
  {
    "id": 55,
    "revelation_place": "madinah",
    "revelation_order": 97,
    "bismillah_pre": true,
    "name_simple": "Ar-Rahman",
    "name_arabic": "\u0627\u0644\u0631\u062d\u0645\u0646",
    "verses_count": 78,
    "pages": [531, 534],
  },
  {
    "id": 56,
    "revelation_place": "makkah",
    "revelation_order": 46,
    "bismillah_pre": true,
    "name_simple": "Al-Waqi'ah",
    "name_arabic": "\u0627\u0644\u0648\u0627\u0642\u0639\u0629",
    "verses_count": 96,
    "pages": [534, 537],
  },
  {
    "id": 57,
    "revelation_place": "madinah",
    "revelation_order": 94,
    "bismillah_pre": true,
    "name_simple": "Al-Hadid",
    "name_arabic": "\u0627\u0644\u062d\u062f\u064a\u062f",
    "verses_count": 29,
    "pages": [537, 541],
  },
  {
    "id": 58,
    "revelation_place": "madinah",
    "revelation_order": 105,
    "bismillah_pre": true,
    "name_simple": "Al-Mujadila",
    "name_arabic": "\u0627\u0644\u0645\u062c\u0627\u062f\u0644\u0629",
    "verses_count": 22,
    "pages": [542, 545],
  },
  {
    "id": 59,
    "revelation_place": "madinah",
    "revelation_order": 101,
    "bismillah_pre": true,
    "name_simple": "Al-Hashr",
    "name_arabic": "\u0627\u0644\u062d\u0634\u0631",
    "verses_count": 24,
    "pages": [545, 548],
  },
  {
    "id": 60,
    "revelation_place": "madinah",
    "revelation_order": 91,
    "bismillah_pre": true,
    "name_simple": "Al-Mumtahanah",
    "name_arabic": "\u0627\u0644\u0645\u0645\u062a\u062d\u0646\u0629",
    "verses_count": 13,
    "pages": [549, 551],
  },
  {
    "id": 61,
    "revelation_place": "madinah",
    "revelation_order": 109,
    "bismillah_pre": true,
    "name_simple": "As-Saf",
    "name_arabic": "\u0627\u0644\u0635\u0641",
    "verses_count": 14,
    "pages": [551, 552],
  },
  {
    "id": 62,
    "revelation_place": "madinah",
    "revelation_order": 110,
    "bismillah_pre": true,
    "name_simple": "Al-Jumu'ah",
    "name_arabic": "\u0627\u0644\u062c\u0645\u0639\u0629",
    "verses_count": 11,
    "pages": [553, 554],
  },
  {
    "id": 63,
    "revelation_place": "madinah",
    "revelation_order": 104,
    "bismillah_pre": true,
    "name_simple": "Al-Munafiqun",
    "name_arabic": "\u0627\u0644\u0645\u0646\u0627\u0641\u0642\u0648\u0646",
    "verses_count": 11,
    "pages": [554, 555],
  },
  {
    "id": 64,
    "revelation_place": "madinah",
    "revelation_order": 108,
    "bismillah_pre": true,
    "name_simple": "At-Taghabun",
    "name_arabic": "\u0627\u0644\u062a\u063a\u0627\u0628\u0646",
    "verses_count": 18,
    "pages": [556, 557],
  },
  {
    "id": 65,
    "revelation_place": "madinah",
    "revelation_order": 99,
    "bismillah_pre": true,
    "name_simple": "At-Talaq",
    "name_arabic": "\u0627\u0644\u0637\u0644\u0627\u0642",
    "verses_count": 12,
    "pages": [558, 559],
  },
  {
    "id": 66,
    "revelation_place": "madinah",
    "revelation_order": 107,
    "bismillah_pre": true,
    "name_simple": "At-Tahrim",
    "name_arabic": "\u0627\u0644\u062a\u062d\u0631\u064a\u0645",
    "verses_count": 12,
    "pages": [560, 561],
  },
  {
    "id": 67,
    "revelation_place": "makkah",
    "revelation_order": 77,
    "bismillah_pre": true,
    "name_simple": "Al-Mulk",
    "name_arabic": "\u0627\u0644\u0645\u0644\u0643",
    "verses_count": 30,
    "pages": [562, 564],
  },
  {
    "id": 68,
    "revelation_place": "makkah",
    "revelation_order": 2,
    "bismillah_pre": true,
    "name_simple": "Al-Qalam",
    "name_arabic": "\u0627\u0644\u0642\u0644\u0645",
    "verses_count": 52,
    "pages": [564, 566],
  },
  {
    "id": 69,
    "revelation_place": "makkah",
    "revelation_order": 78,
    "bismillah_pre": true,
    "name_simple": "Al-Haqqah",
    "name_arabic": "\u0627\u0644\u062d\u0627\u0642\u0629",
    "verses_count": 52,
    "pages": [566, 568],
  },
  {
    "id": 70,
    "revelation_place": "makkah",
    "revelation_order": 79,
    "bismillah_pre": true,
    "name_simple": "Al-Ma'arij",
    "name_arabic": "\u0627\u0644\u0645\u0639\u0627\u0631\u062c",
    "verses_count": 44,
    "pages": [568, 570],
  },
  {
    "id": 71,
    "revelation_place": "makkah",
    "revelation_order": 71,
    "bismillah_pre": true,
    "name_simple": "Nuh",
    "name_arabic": "\u0646\u0648\u062d",
    "verses_count": 28,
    "pages": [570, 571],
  },
  {
    "id": 72,
    "revelation_place": "makkah",
    "revelation_order": 40,
    "bismillah_pre": true,
    "name_simple": "Al-Jinn",
    "name_arabic": "\u0627\u0644\u062c\u0646",
    "verses_count": 28,
    "pages": [572, 573],
  },
  {
    "id": 73,
    "revelation_place": "makkah",
    "revelation_order": 3,
    "bismillah_pre": true,
    "name_simple": "Al-Muzzammil",
    "name_arabic": "\u0627\u0644\u0645\u0632\u0645\u0644",
    "verses_count": 20,
    "pages": [574, 575],
  },
  {
    "id": 74,
    "revelation_place": "makkah",
    "revelation_order": 4,
    "bismillah_pre": true,
    "name_simple": "Al-Muddaththir",
    "name_arabic": "\u0627\u0644\u0645\u062f\u062b\u0631",
    "verses_count": 56,
    "pages": [575, 577],
  },
  {
    "id": 75,
    "revelation_place": "makkah",
    "revelation_order": 31,
    "bismillah_pre": true,
    "name_simple": "Al-Qiyamah",
    "name_arabic": "\u0627\u0644\u0642\u064a\u0627\u0645\u0629",
    "verses_count": 40,
    "pages": [577, 578],
  },
  {
    "id": 76,
    "revelation_place": "madinah",
    "revelation_order": 98,
    "bismillah_pre": true,
    "name_simple": "Al-Insan",
    "name_arabic": "\u0627\u0644\u0627\u0646\u0633\u0627\u0646",
    "verses_count": 31,
    "pages": [578, 580],
  },
  {
    "id": 77,
    "revelation_place": "makkah",
    "revelation_order": 33,
    "bismillah_pre": true,
    "name_simple": "Al-Mursalat",
    "name_arabic": "\u0627\u0644\u0645\u0631\u0633\u0644\u0627\u062a",
    "verses_count": 50,
    "pages": [580, 581],
  },
  {
    "id": 78,
    "revelation_place": "makkah",
    "revelation_order": 80,
    "bismillah_pre": true,
    "name_simple": "An-Naba",
    "name_arabic": "\u0627\u0644\u0646\u0628\u0625",
    "verses_count": 40,
    "pages": [582, 583],
  },
  {
    "id": 79,
    "revelation_place": "makkah",
    "revelation_order": 81,
    "bismillah_pre": true,
    "name_simple": "An-Nazi'at",
    "name_arabic": "\u0627\u0644\u0646\u0627\u0632\u0639\u0627\u062a",
    "verses_count": 46,
    "pages": [583, 584],
  },
  {
    "id": 80,
    "revelation_place": "makkah",
    "revelation_order": 24,
    "bismillah_pre": true,
    "name_simple": "'Abasa",
    "name_arabic": "\u0639\u0628\u0633",
    "verses_count": 42,
    "pages": [585, 585],
  },
  {
    "id": 81,
    "revelation_place": "makkah",
    "revelation_order": 7,
    "bismillah_pre": true,
    "name_simple": "At-Takwir",
    "name_arabic": "\u0627\u0644\u062a\u0643\u0648\u064a\u0631",
    "verses_count": 29,
    "pages": [586, 586],
  },
  {
    "id": 82,
    "revelation_place": "makkah",
    "revelation_order": 82,
    "bismillah_pre": true,
    "name_simple": "Al-Infitar",
    "name_arabic": "\u0627\u0644\u0625\u0646\u0641\u0637\u0627\u0631",
    "verses_count": 19,
    "pages": [587, 587],
  },
  {
    "id": 83,
    "revelation_place": "makkah",
    "revelation_order": 86,
    "bismillah_pre": true,
    "name_simple": "Al-Mutaffifin",
    "name_arabic": "\u0627\u0644\u0645\u0637\u0641\u0641\u064a\u0646",
    "verses_count": 36,
    "pages": [587, 589],
  },
  {
    "id": 84,
    "revelation_place": "makkah",
    "revelation_order": 83,
    "bismillah_pre": true,
    "name_simple": "Al-Inshiqaq",
    "name_arabic": "\u0627\u0644\u0625\u0646\u0634\u0642\u0627\u0642",
    "verses_count": 25,
    "pages": [589, 589],
  },
  {
    "id": 85,
    "revelation_place": "makkah",
    "revelation_order": 27,
    "bismillah_pre": true,
    "name_simple": "Al-Buruj",
    "name_arabic": "\u0627\u0644\u0628\u0631\u0648\u062c",
    "verses_count": 22,
    "pages": [590, 590],
  },
  {
    "id": 86,
    "revelation_place": "makkah",
    "revelation_order": 36,
    "bismillah_pre": true,
    "name_simple": "At-Tariq",
    "name_arabic": "\u0627\u0644\u0637\u0627\u0631\u0642",
    "verses_count": 17,
    "pages": [591, 591],
  },
  {
    "id": 87,
    "revelation_place": "makkah",
    "revelation_order": 8,
    "bismillah_pre": true,
    "name_simple": "Al-A'la",
    "name_arabic": "\u0627\u0644\u0623\u0639\u0644\u0649",
    "verses_count": 19,
    "pages": [591, 592],
  },
  {
    "id": 88,
    "revelation_place": "makkah",
    "revelation_order": 68,
    "bismillah_pre": true,
    "name_simple": "Al-Ghashiyah",
    "name_arabic": "\u0627\u0644\u063a\u0627\u0634\u064a\u0629",
    "verses_count": 26,
    "pages": [592, 592],
  },
  {
    "id": 89,
    "revelation_place": "makkah",
    "revelation_order": 10,
    "bismillah_pre": true,
    "name_simple": "Al-Fajr",
    "name_arabic": "\u0627\u0644\u0641\u062c\u0631",
    "verses_count": 30,
    "pages": [593, 594],
  },
  {
    "id": 90,
    "revelation_place": "makkah",
    "revelation_order": 35,
    "bismillah_pre": true,
    "name_simple": "Al-Balad",
    "name_arabic": "\u0627\u0644\u0628\u0644\u062f",
    "verses_count": 20,
    "pages": [594, 594],
  },
  {
    "id": 91,
    "revelation_place": "makkah",
    "revelation_order": 26,
    "bismillah_pre": true,
    "name_simple": "Ash-Shams",
    "name_arabic": "\u0627\u0644\u0634\u0645\u0633",
    "verses_count": 15,
    "pages": [595, 595],
  },
  {
    "id": 92,
    "revelation_place": "makkah",
    "revelation_order": 9,
    "bismillah_pre": true,
    "name_simple": "Al-Layl",
    "name_arabic": "\u0627\u0644\u0644\u064a\u0644",
    "verses_count": 21,
    "pages": [595, 596],
  },
  {
    "id": 93,
    "revelation_place": "makkah",
    "revelation_order": 11,
    "bismillah_pre": true,
    "name_simple": "Ad-Duhaa",
    "name_arabic": "\u0627\u0644\u0636\u062d\u0649",
    "verses_count": 11,
    "pages": [596, 596],
  },
  {
    "id": 94,
    "revelation_place": "makkah",
    "revelation_order": 12,
    "bismillah_pre": true,
    "name_simple": "Ash-Sharh",
    "name_arabic": "\u0627\u0644\u0634\u0631\u062d",
    "verses_count": 8,
    "pages": [596, 596],
  },
  {
    "id": 95,
    "revelation_place": "makkah",
    "revelation_order": 28,
    "bismillah_pre": true,
    "name_simple": "At-Tin",
    "name_arabic": "\u0627\u0644\u062a\u064a\u0646",
    "verses_count": 8,
    "pages": [597, 597],
  },
  {
    "id": 96,
    "revelation_place": "makkah",
    "revelation_order": 1,
    "bismillah_pre": true,
    "name_simple": "Al-'Alaq",
    "name_arabic": "\u0627\u0644\u0639\u0644\u0642",
    "verses_count": 19,
    "pages": [597, 597],
  },
  {
    "id": 97,
    "revelation_place": "makkah",
    "revelation_order": 25,
    "bismillah_pre": true,
    "name_simple": "Al-Qadr",
    "name_arabic": "\u0627\u0644\u0642\u062f\u0631",
    "verses_count": 5,
    "pages": [598, 598],
  },
  {
    "id": 98,
    "revelation_place": "madinah",
    "revelation_order": 100,
    "bismillah_pre": true,
    "name_simple": "Al-Bayyinah",
    "name_arabic": "\u0627\u0644\u0628\u064a\u0646\u0629",
    "verses_count": 8,
    "pages": [598, 599],
  },
  {
    "id": 99,
    "revelation_place": "madinah",
    "revelation_order": 93,
    "bismillah_pre": true,
    "name_simple": "Az-Zalzalah",
    "name_arabic": "\u0627\u0644\u0632\u0644\u0632\u0644\u0629",
    "verses_count": 8,
    "pages": [599, 599],
  },
  {
    "id": 100,
    "revelation_place": "makkah",
    "revelation_order": 14,
    "bismillah_pre": true,
    "name_simple": "Al-'Adiyat",
    "name_arabic": "\u0627\u0644\u0639\u0627\u062f\u064a\u0627\u062a",
    "verses_count": 11,
    "pages": [599, 600],
  },
  {
    "id": 101,
    "revelation_place": "makkah",
    "revelation_order": 30,
    "bismillah_pre": true,
    "name_simple": "Al-Qari'ah",
    "name_arabic": "\u0627\u0644\u0642\u0627\u0631\u0639\u0629",
    "verses_count": 11,
    "pages": [600, 600],
  },
  {
    "id": 102,
    "revelation_place": "makkah",
    "revelation_order": 16,
    "bismillah_pre": true,
    "name_simple": "At-Takathur",
    "name_arabic": "\u0627\u0644\u062a\u0643\u0627\u062b\u0631",
    "verses_count": 8,
    "pages": [600, 600],
  },
  {
    "id": 103,
    "revelation_place": "makkah",
    "revelation_order": 13,
    "bismillah_pre": true,
    "name_simple": "Al-'Asr",
    "name_arabic": "\u0627\u0644\u0639\u0635\u0631",
    "verses_count": 3,
    "pages": [601, 601],
  },
  {
    "id": 104,
    "revelation_place": "makkah",
    "revelation_order": 32,
    "bismillah_pre": true,
    "name_simple": "Al-Humazah",
    "name_arabic": "\u0627\u0644\u0647\u0645\u0632\u0629",
    "verses_count": 9,
    "pages": [601, 601],
  },
  {
    "id": 105,
    "revelation_place": "makkah",
    "revelation_order": 19,
    "bismillah_pre": true,
    "name_simple": "Al-Fil",
    "name_arabic": "\u0627\u0644\u0641\u064a\u0644",
    "verses_count": 5,
    "pages": [601, 601],
  },
  {
    "id": 106,
    "revelation_place": "makkah",
    "revelation_order": 29,
    "bismillah_pre": true,
    "name_simple": "Quraysh",
    "name_arabic": "\u0642\u0631\u064a\u0634",
    "verses_count": 4,
    "pages": [602, 602],
  },
  {
    "id": 107,
    "revelation_place": "makkah",
    "revelation_order": 17,
    "bismillah_pre": true,
    "name_simple": "Al-Ma'un",
    "name_arabic": "\u0627\u0644\u0645\u0627\u0639\u0648\u0646",
    "verses_count": 7,
    "pages": [602, 602],
  },
  {
    "id": 108,
    "revelation_place": "makkah",
    "revelation_order": 15,
    "bismillah_pre": true,
    "name_simple": "Al-Kawthar",
    "name_arabic": "\u0627\u0644\u0643\u0648\u062b\u0631",
    "verses_count": 3,
    "pages": [602, 602],
  },
  {
    "id": 109,
    "revelation_place": "makkah",
    "revelation_order": 18,
    "bismillah_pre": true,
    "name_simple": "Al-Kafirun",
    "name_arabic": "\u0627\u0644\u0643\u0627\u0641\u0631\u0648\u0646",
    "verses_count": 6,
    "pages": [603, 603],
  },
  {
    "id": 110,
    "revelation_place": "madinah",
    "revelation_order": 114,
    "bismillah_pre": true,
    "name_simple": "An-Nasr",
    "name_arabic": "\u0627\u0644\u0646\u0635\u0631",
    "verses_count": 3,
    "pages": [603, 603],
  },
  {
    "id": 111,
    "revelation_place": "makkah",
    "revelation_order": 6,
    "bismillah_pre": true,
    "name_simple": "Al-Masad",
    "name_arabic": "\u0627\u0644\u0645\u0633\u062f",
    "verses_count": 5,
    "pages": [603, 603],
  },
  {
    "id": 112,
    "revelation_place": "makkah",
    "revelation_order": 22,
    "bismillah_pre": true,
    "name_simple": "Al-Ikhlas",
    "name_arabic": "\u0627\u0644\u0625\u062e\u0644\u0627\u0635",
    "verses_count": 4,
    "pages": [604, 604],
  },
  {
    "id": 113,
    "revelation_place": "makkah",
    "revelation_order": 20,
    "bismillah_pre": true,
    "name_simple": "Al-Falaq",
    "name_arabic": "\u0627\u0644\u0641\u0644\u0642",
    "verses_count": 5,
    "pages": [604, 604],
  },
  {
    "id": 114,
    "revelation_place": "makkah",
    "revelation_order": 21,
    "bismillah_pre": true,
    "name_simple": "An-Nas",
    "name_arabic": "\u0627\u0644\u0646\u0627\u0633",
    "verses_count": 6,
    "pages": [604, 604],
  }
];

List<Map<String, dynamic>> allJuzInfo = [
  {
    "id": 1,
    "juz_number": 1,
    "verse_mapping": {"1": "1-7", "2": "1-141"},
    "first_verse_id": 1,
    "last_verse_id": 148,
    "verses_count": 148
  },
  {
    "id": 2,
    "juz_number": 2,
    "verse_mapping": {"2": "142-252"},
    "first_verse_id": 149,
    "last_verse_id": 259,
    "verses_count": 111
  },
  {
    "id": 3,
    "juz_number": 3,
    "verse_mapping": {"2": "253-286", "3": "1-92"},
    "first_verse_id": 260,
    "last_verse_id": 385,
    "verses_count": 126
  },
  {
    "id": 4,
    "juz_number": 4,
    "verse_mapping": {"3": "93-200", "4": "1-23"},
    "first_verse_id": 386,
    "last_verse_id": 516,
    "verses_count": 131
  },
  {
    "id": 5,
    "juz_number": 5,
    "verse_mapping": {"4": "24-147"},
    "first_verse_id": 517,
    "last_verse_id": 640,
    "verses_count": 124
  },
  {
    "id": 6,
    "juz_number": 6,
    "verse_mapping": {"4": "148-176", "5": "1-81"},
    "first_verse_id": 641,
    "last_verse_id": 750,
    "verses_count": 110
  },
  {
    "id": 7,
    "juz_number": 7,
    "verse_mapping": {"5": "82-120", "6": "1-110"},
    "first_verse_id": 751,
    "last_verse_id": 899,
    "verses_count": 149
  },
  {
    "id": 8,
    "juz_number": 8,
    "verse_mapping": {"6": "111-165", "7": "1-87"},
    "first_verse_id": 900,
    "last_verse_id": 1041,
    "verses_count": 142
  },
  {
    "id": 9,
    "juz_number": 9,
    "verse_mapping": {"7": "88-206", "8": "1-40"},
    "first_verse_id": 1042,
    "last_verse_id": 1200,
    "verses_count": 159
  },
  {
    "id": 10,
    "juz_number": 10,
    "verse_mapping": {"8": "41-75", "9": "1-92"},
    "first_verse_id": 1201,
    "last_verse_id": 1327,
    "verses_count": 127
  },
  {
    "id": 11,
    "juz_number": 11,
    "verse_mapping": {"9": "93-129", "10": "1-109", "11": "1-5"},
    "first_verse_id": 1328,
    "last_verse_id": 1478,
    "verses_count": 151
  },
  {
    "id": 12,
    "juz_number": 12,
    "verse_mapping": {"11": "6-123", "12": "1-52"},
    "first_verse_id": 1479,
    "last_verse_id": 1648,
    "verses_count": 170
  },
  {
    "id": 13,
    "juz_number": 13,
    "verse_mapping": {"12": "53-111", "13": "1-43", "14": "1-52"},
    "first_verse_id": 1649,
    "last_verse_id": 1802,
    "verses_count": 154
  },
  {
    "id": 14,
    "juz_number": 14,
    "verse_mapping": {"15": "1-99", "16": "1-128"},
    "first_verse_id": 1803,
    "last_verse_id": 2029,
    "verses_count": 227
  },
  {
    "id": 15,
    "juz_number": 15,
    "verse_mapping": {"17": "1-111", "18": "1-74"},
    "first_verse_id": 2030,
    "last_verse_id": 2214,
    "verses_count": 185
  },
  {
    "id": 16,
    "juz_number": 16,
    "verse_mapping": {"18": "75-110", "19": "1-98", "20": "1-135"},
    "first_verse_id": 2215,
    "last_verse_id": 2483,
    "verses_count": 269
  },
  {
    "id": 17,
    "juz_number": 17,
    "verse_mapping": {"21": "1-112", "22": "1-78"},
    "first_verse_id": 2484,
    "last_verse_id": 2673,
    "verses_count": 190
  },
  {
    "id": 18,
    "juz_number": 18,
    "verse_mapping": {"23": "1-118", "24": "1-64", "25": "1-20"},
    "first_verse_id": 2674,
    "last_verse_id": 2875,
    "verses_count": 202
  },
  {
    "id": 19,
    "juz_number": 19,
    "verse_mapping": {"25": "21-77", "26": "1-227", "27": "1-55"},
    "first_verse_id": 2876,
    "last_verse_id": 3214,
    "verses_count": 339
  },
  {
    "id": 20,
    "juz_number": 20,
    "verse_mapping": {"27": "56-93", "28": "1-88", "29": "1-45"},
    "first_verse_id": 3215,
    "last_verse_id": 3385,
    "verses_count": 171
  },
  {
    "id": 21,
    "juz_number": 21,
    "verse_mapping": {
      "29": "46-69",
      "30": "1-60",
      "31": "1-34",
      "32": "1-30",
      "33": "1-30"
    },
    "first_verse_id": 3386,
    "last_verse_id": 3563,
    "verses_count": 178
  },
  {
    "id": 22,
    "juz_number": 22,
    "verse_mapping": {"33": "31-73", "34": "1-54", "35": "1-45", "36": "1-27"},
    "first_verse_id": 3564,
    "last_verse_id": 3732,
    "verses_count": 169
  },
  {
    "id": 23,
    "juz_number": 23,
    "verse_mapping": {"36": "28-83", "37": "1-182", "38": "1-88", "39": "1-31"},
    "first_verse_id": 3733,
    "last_verse_id": 4089,
    "verses_count": 357
  },
  {
    "id": 24,
    "juz_number": 24,
    "verse_mapping": {"39": "32-75", "40": "1-85", "41": "1-46"},
    "first_verse_id": 4090,
    "last_verse_id": 4264,
    "verses_count": 175
  },
  {
    "id": 25,
    "juz_number": 25,
    "verse_mapping": {
      "41": "47-54",
      "42": "1-53",
      "43": "1-89",
      "44": "1-59",
      "45": "1-37"
    },
    "first_verse_id": 4265,
    "last_verse_id": 4510,
    "verses_count": 246
  },
  {
    "id": 26,
    "juz_number": 26,
    "verse_mapping": {
      "46": "1-35",
      "47": "1-38",
      "48": "1-29",
      "49": "1-18",
      "50": "1-45",
      "51": "1-30"
    },
    "first_verse_id": 4511,
    "last_verse_id": 4705,
    "verses_count": 195
  },
  {
    "id": 27,
    "juz_number": 27,
    "verse_mapping": {
      "51": "31-60",
      "52": "1-49",
      "53": "1-62",
      "54": "1-55",
      "55": "1-78",
      "56": "1-96",
      "57": "1-29"
    },
    "first_verse_id": 4706,
    "last_verse_id": 5104,
    "verses_count": 399
  },
  {
    "id": 28,
    "juz_number": 28,
    "verse_mapping": {
      "58": "1-22",
      "59": "1-24",
      "60": "1-13",
      "61": "1-14",
      "62": "1-11",
      "63": "1-11",
      "64": "1-18",
      "65": "1-12",
      "66": "1-12"
    },
    "first_verse_id": 5105,
    "last_verse_id": 5241,
    "verses_count": 137
  },
  {
    "id": 29,
    "juz_number": 29,
    "verse_mapping": {
      "67": "1-30",
      "68": "1-52",
      "69": "1-52",
      "70": "1-44",
      "71": "1-28",
      "72": "1-28",
      "73": "1-20",
      "74": "1-56",
      "75": "1-40",
      "76": "1-31",
      "77": "1-50"
    },
    "first_verse_id": 5242,
    "last_verse_id": 5672,
    "verses_count": 431
  },
  {
    "id": 30,
    "juz_number": 30,
    "verse_mapping": {
      "78": "1-40",
      "79": "1-46",
      "80": "1-42",
      "81": "1-29",
      "82": "1-19",
      "83": "1-36",
      "84": "1-25",
      "85": "1-22",
      "86": "1-17",
      "87": "1-19",
      "88": "1-26",
      "89": "1-30",
      "90": "1-20",
      "91": "1-15",
      "92": "1-21",
      "93": "1-11",
      "94": "1-8",
      "95": "1-8",
      "96": "1-19",
      "97": "1-5",
      "98": "1-8",
      "99": "1-8",
      "100": "1-11",
      "101": "1-11",
      "102": "1-8",
      "103": "1-3",
      "104": "1-9",
      "105": "1-5",
      "106": "1-4",
      "107": "1-7",
      "108": "1-3",
      "109": "1-6",
      "110": "1-3",
      "111": "1-5",
      "112": "1-4",
      "113": "1-5",
      "114": "1-6"
    },
    "first_verse_id": 5673,
    "last_verse_id": 6236,
    "verses_count": 564
  },
];

List<int> ayahCount = [
  7,
  286,
  200,
  176,
  120,
  165,
  206,
  75,
  129,
  109,
  123,
  111,
  43,
  52,
  99,
  128,
  111,
  110,
  98,
  135,
  112,
  78,
  118,
  64,
  77,
  227,
  93,
  88,
  69,
  60,
  34,
  30,
  73,
  54,
  45,
  83,
  182,
  88,
  75,
  85,
  54,
  53,
  89,
  59,
  37,
  35,
  38,
  29,
  18,
  45,
  60,
  49,
  62,
  55,
  78,
  96,
  29,
  22,
  24,
  13,
  14,
  11,
  11,
  18,
  12,
  12,
  30,
  52,
  52,
  44,
  28,
  28,
  20,
  56,
  40,
  31,
  50,
  40,
  46,
  42,
  29,
  19,
  36,
  25,
  22,
  17,
  19,
  26,
  30,
  20,
  15,
  21,
  11,
  8,
  8,
  19,
  5,
  8,
  8,
  11,
  11,
  8,
  3,
  9,
  5,
  4,
  7,
  3,
  6,
  3,
  5,
  4,
  5,
  6
];
